name: spotify_music_player
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  audio_video_progress_bar: ^2.0.3
  spotify: ^0.13.6+1
  youtube_explode_dart: ^2.2.1
  audioplayers: ^6.0.0
  palette_generator: ^0.3.3+3
  scrollable_positioned_list: ^0.3.8
  http:
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
